# Generated by Django 4.2.30 on 2026-09-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='click',
            name='user_agent',
        ),
    ]
